
projects:
	atma: 
		path: "file:///d:/libjs/"
		
	bootstrap:
		path: "file:///d:/libjs/vendor/bootstrap/"
	
	vendor:
		path: "file:///d:/libjs/vendor/"
	
defaultRoutes: 
	atma: "{atma}/{0}/lib/{1}.js"
	atma_ruqq: "{atma}/ruqq/lib/{0}.js"
	atma_compo: "{atma}/compos/{0}/lib/{1}.js"
	bootstrap: "{bootstrap}/{0}.less"

plugins: 
	- 'utest'