
projects:
	atma: 
		path: "file:///d:/atma/"
		
	bootstrap:
		path: "file:///d:/vendor/bootstrap/"
	
	vendor:
		path: "file:///d:/vendor/"
	
defaultRoutes: 
	atma: "{atma}/{0}/lib/{1}.js"
	atma_ruqq: "{atma}/ruqq/lib/{0}.js"
	atma_compo: "{atma}/compos/{0}/lib/{1}.js"
	bootstrap: "{bootstrap}/{0}.less"

plugins: 
	- 'atma-utest'