env:
	both:
	
		include:
			cfg:
				loader:
	
	
		routes:
			public : '/public/script/{0}.js' 
			public.compo: '/public/compo/{0}/{1}.js'
	
			atma: '/.reference/atma/{0}/lib/{1}.js'
			atma.compos: '/.reference/atma/compos/{0}/lib/{1}.js'
	
			view: '/public/view/{0}/{1}.js'
	
		scripts:
			atma:
	
			atma.compos:
	
			public.compo:
