


client:

	include:
		src: '/.reference/atma/include/lib/include.js'

	scripts:
		atma:
			- ruqq/dom/jquery
			- class
			- mask
			- if#debug:
				- mask/plugin.reload

			- mask.node/mask.bootstrap
			- ruta
			- mask.animation
			- if#debug:
				- include/include.autoreload

		public.compo:

	styles:
		- '/public/style/main.less'
